In [2]:
import numpy as np
a = np.array([1, 2, 3])

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(3,)


In [5]:
print(a[0])

1


In [6]:
a[0] = 5
print(a)

[5 2 3]


In [7]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0], b[0,1], b[1,0])

(2, 3)
1 2 4


In [8]:
a = np.zeros((2,2))
print (a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [10]:
c = np.full((2, 2), 7)
print (c)

[[7 7]
 [7 7]]


In [11]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [12]:
e = np.random.random((2,2))
print(e)

[[0.04517464 0.15909831]
 [0.42362457 0.14236782]]


In [13]:
# slicing
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

r1 = a[1, 1:3]
r2 = a[1:2, :]
s1 = a[0, :]
s2 = a[0:1]
s3 = a[1:2]
s4 = a[:]

print(a)
print(a[0:len(a)])
print(r1, r1.shape)
print(r2, r2.shape)
print(s1, s1.shape)
print(s2, s2.shape)
print(s3, s3.shape)
print(s4, s4.shape)

cr1 = a[:, 1]
cr2 = a[:, 1:2]

print(cr1, cr1.shape)
print(cr2, cr2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[6 7] (2,)
[[5 6 7 8]] (1, 4)
[1 2 3 4] (4,)
[[1 2 3 4]] (1, 4)
[[5 6 7 8]] (1, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [14]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)

print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [19]:
a = np.arange(6)
print(a.shape)
a

(6,)


array([0, 1, 2, 3, 4, 5])

In [44]:
observation = np.array([111.0, 188.0])
codes = np.array([[102.0, 203.0],

               [132.0, 193.0],

               [45.0, 155.0],

               [57.0, 173.0]])
diff = codes - observation
dist = np.sqrt(np.sum(diff**2, axis=-1))
np.argmin(dist)

0

In [52]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])

x.shape
(2, 3, 1)

x[1:2]

array([[[4],
        [5],
        [6]]])

In [85]:
print(codes)
print()
print("Flip along row axis 0")
print(np.flip(codes, axis=0))
print()
print("Flip along column axis 1")
print(np.flip(codes, axis=1))

[[102. 203.]
 [132. 193.]
 [ 45. 155.]
 [ 57. 173.]]

Flip along row axis 0
[[ 57. 173.]
 [ 45. 155.]
 [132. 193.]
 [102. 203.]]

Flip along column axis 1
[[203. 102.]
 [193. 132.]
 [155.  45.]
 [173.  57.]]


In [62]:
# tensors

import torch

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3734, 0.6129],
        [0.0768, 0.5323]]) 



In [64]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7183, 0.7224, 0.0108],
        [0.9874, 0.4758, 0.1206]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [72]:
tensor = torch.rand(3,4)

if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cuda:0


In [89]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

print()
print(f"Shape is {tensor.shape}")
print()
print("Concatenate along column axis 1")
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)


First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Shape is torch.Size([4, 4])

Concatenate along column axis 1
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
